In [2]:
import numpy as np

1\. Sukurkite vektorių su skaičiais nuo 1 iki 10

In [3]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

2\. Sukurkite vektorių iš 10 nulių

In [4]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

3\. Sukurkite vektorių iš 10 vienetų

In [ ]:
np.ones(10)

4\. Sukurkite vektorių iš 10 ketvertų

In [ ]:
np.ones(10) * 4

5\. Sukurkite vektorių iš lyginių skaičių nuo 0 iki 100

In [ ]:
np.arange(0, 101, 2)

6\. Sukurkite matricą iš 25 narių, pradedant 1, baigiant 25. Priskirkite ją kintamąjam.

In [5]:
arr = np.arange(1,26).reshape(5,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

7\. Iš matricos ištraukite skaičių 12

In [ ]:
arr[2,1]

8\. Iš matricos ištraukite paskutinę eilutę.

In [ ]:
arr[-1]

9\. Iš matricos ištraukite submatricą

1, 2, 3\
6, 7, 8\
11,12,13

In [ ]:
arr[:3, :3]

10\. Iš matricos ištraukite submatricą

7, 8, 9, 10\
12, 13, 14, 15\
17, 18, 19, 20

In [ ]:
arr[1:4, 1:]

11\. Iš matricos ištraukite submatricą

16, 17, 18  
21, 22, 23

In [ ]:
arr[3:, :3]

12\. Sukurkite vektorių iš 20 atsitiktinių reikšmių nuo 0 iki 1. Priskirkite kintamąjam.

In [ ]:
randarr = np.random.rand(20)
randarr

13\. Suraskite didžiausią reikšmę masyve ir jos indeksą.

In [ ]:
max(randarr)
randarr.argmax()

14\. Suraskite mažiausią reikšmę ir jos indeksą

In [ ]:
randarr.min()
randarr.argmin()

15\. Atspausdinkite šios matricos duomenų tipą

In [ ]:
randarr.dtype

16\. Sukurkite vektorių iš integer reikšmių nuo 1 iki 100. Priskirkite kintamąjam. Iš jo ištraukite visus skaičius, didesnius už 90

In [ ]:
bandymas = np.arange(1,101)
bandymas
bandymas[bandymas > 90]
bandymas[bandymas % 7 == 0]

18\. Sukurkite tokią matricą:

In [ ]:
# array([[0.025, 0.05 , 0.075, 0.1  , 0.125, 0.15 , 0.175, 0.2  ],
#        [0.225, 0.25 , 0.275, 0.3  , 0.325, 0.35 , 0.375, 0.4  ],
#        [0.425, 0.45 , 0.475, 0.5  , 0.525, 0.55 , 0.575, 0.6  ],
#        [0.625, 0.65 , 0.675, 0.7  , 0.725, 0.75 , 0.775, 0.8  ],
#        [0.825, 0.85 , 0.875, 0.9  , 0.925, 0.95 , 0.975, 1.   ]])


In [ ]:
np.linspace(0.025,1,40).reshape(5,8)

19\. sukurkite tokią matricą (sveiki sk. nuo 2 iki 1000 iš kurių traukiasi sveika šaknis):

In [ ]:
# array([[  4,   9,  16,  25,  36],
#        [ 49,  64,  81, 100, 121],
#        [144, 169, 196, 225, 256],
#        [289, 324, 361, 400, 441],
#        [484, 529, 576, 625, 676],
#        [729, 784, 841, 900, 961]])

In [ ]:
matrica = np.arange(2,1000)
res = matrica[(matrica ** 0.5) % 1 == 0].reshape(6,5)
res

20\. **(BONUS)**
* Sukurkite vektorių iš sveikų sk. nuo 1 iki 100. Priskirkite kintamąjam.
* Sukurkite Python funkciją, kuri tikrina ar parametruose įvestas sk. yra pirminis. Jeigu pirminis, grąžina True, jei ne, False.
* NumPy nevisada supranta įprastą Python kodą su range'ais ir list'ais, todėl sukurtą funkciją teks vektorizuoti taip : **nauja_funkcija = np.vectorize(jūsų_funkcija)**  .
* Kadangi sąlygos reikšmių traukimui yra *bool* reikšmės, pabandykite vietoje sąlygos įdėti savo vektorizuotą funkciją, ir taip išrinkti pirminius skaičius iš savo vektoriaus
.

In [ ]:
testlist = np.arange(1,101)

def is_prime(number):
    for i in range(2, number):
        if number % i == 0:
            return False
    return True

vis_prime = np.vectorize(is_prime)

testlist[vis_prime(testlist)]